export type Copy = { en: string; it: string }
export type EquipmentCategory = 'radios' | 'bodycams' | 'accessories'

export type Equipment = {
  id: string
  maker: string
  model: string
  category: EquipmentCategory
  image?: string
  article?: string
  description: Copy
  role: Copy
  highlights?: Copy[]
  source?: string
}

// The article numbers and names below are transcribed from the supplied DKPS stock list.
// Only specifications that are unambiguous in that list are shown to visitors.
const stockRadio = (article: string, maker: string, model: string, role: Copy, description: Copy, highlights: Copy[]): Equipment => ({
  id: article.toLowerCase(), article, maker, model, category: 'radios', image: `/images/equipment/${article.toLowerCase()}.webp`, role, description, highlights,
})

export const equipment: Equipment[] = [
  stockRadio('DKPS-RADHH-018', 'DKPS catalogue', 'Rugged 4 Inch Touchscreen PoC Radio', { en: 'Field teams needing voice and image', it: 'Squadre sul campo che usano voce e immagini' }, { en: 'Rugged handheld with physical controls, cameras and multi-GNSS positioning.', it: 'Portatile robusto con comandi fisici, fotocamere e posizionamento multi-GNSS.' }, [{ en: '4.0-inch display', it: 'Display da 4,0 pollici' }, { en: 'IP68 protection', it: 'Protezione IP68' }, { en: '5,000 mAh removable battery', it: 'Batteria rimovibile da 5.000 mAh' }]),
  stockRadio('DKPS-RADHH-024', 'DKPS catalogue', 'Rugged 4 Inch Touchscreen PoC Radio', { en: 'Field teams — configuration to confirm', it: 'Squadre sul campo — configurazione da confermare' }, { en: 'The supplied name and specifications describe a touchscreen radio, but its flyer photo shows a different, screen-free form. Confirm this article before selection.', it: 'Nome e specifiche della fonte descrivono una radio touchscreen, ma la foto del flyer mostra una forma diversa, senza schermo. Confermare l’articolo prima della scelta.' }, [{ en: '4G LTE / cellular PoC', it: '4G LTE / PoC cellulare' }, { en: 'Source specifications under review', it: 'Specifiche della fonte da verificare' }]),
  stockRadio('DKPS-RADHH-010', 'DKPS catalogue', 'Rugged 4G PoC Radio', { en: 'Long shifts and demanding field work', it: 'Turni lunghi e lavoro sul campo impegnativo' }, { en: 'Handheld with dedicated PTT and SOS controls, noise reduction and dual SIM.', it: 'Portatile con comandi PTT e SOS dedicati, riduzione del rumore e doppia SIM.' }, [{ en: 'IP68 protection', it: 'Protezione IP68' }, { en: '7,000 mAh battery', it: 'Batteria da 7.000 mAh' }, { en: '3 W speaker', it: 'Altoparlante da 3 W' }]),
  stockRadio('DKPS-RADHH-011', 'DKPS catalogue', 'Rugged 4G Smart Touchscreen PoC Radio', { en: 'Supervisors and visual field reporting', it: 'Responsabili e documentazione visiva sul campo' }, { en: 'Smart handheld with touchscreen, front and rear cameras and removable battery.', it: 'Portatile smart con touchscreen, fotocamere anteriore e posteriore e batteria rimovibile.' }, [{ en: '2.8-inch touchscreen', it: 'Touchscreen da 2,8 pollici' }, { en: 'IP68 protection', it: 'Protezione IP68' }, { en: '4,000 mAh battery', it: 'Batteria da 4.000 mAh' }]),
  stockRadio('DKPS-RADVH-002', 'DKPS catalogue', '4G LTE Mobile PoC Radio', { en: 'Vehicle and fixed installations to assess', it: 'Installazioni a bordo e fisse da valutare' }, { en: 'Listed for vehicle and fixed use; its physical configuration requires confirmation because the source also describes a handheld.', it: 'Indicato per uso veicolare e fisso; la configurazione fisica va confermata perché la fonte lo descrive anche come portatile.' }, [{ en: 'LTE / WCDMA / GSM', it: 'LTE / WCDMA / GSM' }, { en: 'GPS positioning', it: 'Posizionamento GPS' }, { en: 'BLE 5.0', it: 'BLE 5.0' }]),
  stockRadio('DKPS-RADHH-004', 'DKPS catalogue', 'Compact 4G PoC Radio', { en: 'Mobile teams', it: 'Squadre mobili' }, { en: 'Compact handheld for cellular PoC communication and GPS positioning.', it: 'Portatile compatto per comunicazioni PoC cellulari e posizionamento GPS.' }, [{ en: 'LTE / WCDMA / GSM', it: 'LTE / WCDMA / GSM' }, { en: 'GPS positioning', it: 'Posizionamento GPS' }, { en: '246 g', it: '246 g' }]),
  stockRadio('DKPS-RADHH-005', 'DKPS catalogue', '4G LTE Keypad PoC Radio', { en: 'Drivers and field teams using physical controls', it: 'Autisti e squadre che usano comandi fisici' }, { en: 'Handheld with numeric keypad, dedicated controls and GPS positioning.', it: 'Portatile con tastiera numerica, comandi dedicati e posizionamento GPS.' }, [{ en: 'LTE / WCDMA / GSM', it: 'LTE / WCDMA / GSM' }, { en: 'Physical numeric keypad', it: 'Tastiera numerica fisica' }, { en: 'Operating range −30 °C to +75 °C', it: 'Temperatura operativa da −30 °C a +75 °C' }]),
  stockRadio('DKPS-RADHH-006', 'DKPS catalogue', '4G LTE Wi-Fi PoC Radio', { en: 'Warehouse and site teams', it: 'Squadre di magazzino e di sede' }, { en: 'Handheld with cellular connectivity, Wi-Fi and GPS positioning.', it: 'Portatile con connettività cellulare, Wi-Fi e posizionamento GPS.' }, [{ en: 'LTE / WCDMA / GSM', it: 'LTE / WCDMA / GSM' }, { en: 'Wi-Fi 802.11 b/g/n', it: 'Wi-Fi 802.11 b/g/n' }, { en: 'GPS positioning', it: 'Posizionamento GPS' }]),
  stockRadio('DKPS-RADHH-023', 'DKPS catalogue', 'Compact 4G PoC Radio', { en: 'Teams preferring simple handheld controls', it: 'Squadre che preferiscono comandi portatili semplici' }, { en: 'Compact screen-free handheld with cellular PoC and GPS.', it: 'Portatile compatto senza schermo, con PoC cellulare e GPS.' }, [{ en: '111 mm body length', it: 'Corpo lungo 111 mm' }, { en: 'GPS positioning', it: 'Posizionamento GPS' }, { en: '267 g', it: '267 g' }]),
  stockRadio('DKPS-RADHH-014', 'Hytera', 'Hytera P50 Professional PoC Radio', { en: 'Portable team communication', it: 'Comunicazione portatile dei team' }, { en: 'Professional PoC handheld with colour display and multi-GNSS positioning.', it: 'Portatile PoC professionale con display a colori e posizionamento multi-GNSS.' }, [{ en: '2.4-inch colour display', it: 'Display a colori da 2,4 pollici' }, { en: 'IP68 protection', it: 'Protezione IP68' }, { en: '4,000 mAh battery', it: 'Batteria da 4.000 mAh' }]),
  stockRadio('DKPS-RADHH-025', 'Hytera', 'Hytera P50 Pro Smart PoC Radio', { en: 'Supervisors and visual field work', it: 'Responsabili e attività visive sul campo' }, { en: 'Smart PoC handheld with an 8 MP camera and multi-GNSS positioning.', it: 'Portatile PoC smart con fotocamera da 8 MP e posizionamento multi-GNSS.' }, [{ en: '2.4-inch colour display', it: 'Display a colori da 2,4 pollici' }, { en: 'IP68 protection', it: 'Protezione IP68' }, { en: '8 MP camera', it: 'Fotocamera da 8 MP' }]),
  stockRadio('DKPS-RADHH-015', 'DKPS catalogue', 'Rugged 4 Inch Touchscreen PoC Radio', { en: 'Compact field communication', it: 'Comunicazione compatta sul campo' }, { en: 'Compact PoC handheld. The supplied title and technical table disagree on the display size; confirm before selection.', it: 'Portatile PoC compatto. Titolo e tabella tecnica della fonte non concordano sulle dimensioni del display: da confermare prima della scelta.' }, [{ en: '4G LTE / cellular PoC', it: '4G LTE / PoC cellulare' }, { en: 'IP68 protection', it: 'Protezione IP68' }, { en: '5,000 mAh removable battery', it: 'Batteria rimovibile da 5.000 mAh' }]),
  stockRadio('DKPS-RADHH-017', 'DKPS catalogue', 'Rugged 4G Mini PoC Radio', { en: 'Compact field teams', it: 'Squadre mobili con dispositivi compatti' }, { en: 'Mini PoC handheld with display and front/rear cameras.', it: 'Mini portatile PoC con display e fotocamere anteriore e posteriore.' }, [{ en: '2.4-inch LCD', it: 'LCD da 2,4 pollici' }, { en: 'IP54 protection', it: 'Protezione IP54' }, { en: '4,100 mAh removable battery', it: 'Batteria rimovibile da 4.100 mAh' }]),
  stockRadio('DKPS-RADHH-003', 'DKPS catalogue', 'Compact 4G PoC Radio with OLED Display', { en: 'Compact indoor and field teams', it: 'Squadre interne e mobili con dispositivi compatti' }, { en: 'Compact handheld with OLED display and cellular PoC communication.', it: 'Portatile compatto con display OLED e comunicazione PoC cellulare.' }, [{ en: '0.96-inch OLED', it: 'OLED da 0,96 pollici' }, { en: 'IP54 protection', it: 'Protezione IP54' }, { en: '4,000 mAh battery', it: 'Batteria da 4.000 mAh' }]),
  { id: 'vb400', maker: 'Motorola Solutions', model: 'VB400', category: 'bodycams', image: '/images/equipment/vb400.png', description: { en: 'Body-worn camera for documenting field incidents.', it: 'Bodycam indossabile per documentare gli interventi sul campo.' }, role: { en: 'Security and response teams', it: 'Sicurezza e squadre di intervento' }, source: 'https://www.motorolasolutions.com/en_us/video-security-access-control/body-worn-cameras/vb400.html' },
  { id: 'sc780', maker: 'Hytera', model: 'SC780', category: 'bodycams', image: '/images/equipment/sc780.png', description: { en: 'Connected 4G bodycam with voice communication features.', it: 'Bodycam 4G con funzioni di comunicazione vocale.' }, role: { en: 'Field response and control-room links', it: 'Interventi sul campo e sala controllo' }, source: 'https://www.hytera.com/eu/terminal.page/products_terminal_body-worn-camera_sc780' },
  { id: 'sc880', maker: 'Hytera', model: 'SC880', category: 'bodycams', image: '/images/equipment/sc880.png', description: { en: 'Connected 5G bodycam with PoC communication support.', it: 'Bodycam 5G con supporto alla comunicazione PoC.' }, role: { en: 'Video-enabled field operations', it: 'Operazioni sul campo con video' }, source: 'https://www.hytera.com/eu/products/body-worn-camera/sc880' },
  { id: 'pmln7189', maker: 'Motorola Solutions', model: 'PMLN7189', category: 'accessories', image: '/images/equipment/earpiece.jpg', description: { en: 'Swivel earpiece with in-line microphone and PTT.', it: 'Auricolare orientabile con microfono e PTT sul cavo.' }, role: { en: 'Discreet team communication', it: 'Comunicazione discreta dei team' }, source: 'https://www.motorolasolutions.com/en_xp/products/two-way-radio-accessories/audio-accessories/earpieces/pmln7189.html' },
  { id: 'rm250', maker: 'Motorola Solutions', model: 'RM250 / PMMN4125', category: 'accessories', image: '/images/equipment/rm250.webp', description: { en: 'Remote speaker microphone for compatible portable radios.', it: 'Microfono altoparlante remoto per radio portatili compatibili.' }, role: { en: 'Hands-on work and field teams', it: 'Lavoro manuale e squadre sul campo' }, source: 'https://www.motorolasolutions.com/en_xp/products/two-way-radio-accessories/audio-accessories/remote-speaker-microphones/pmmn4125.html' },
  { id: 'pmln7158', maker: 'Motorola Solutions', model: 'PMLN7158', category: 'accessories', image: '/images/equipment/pmln7158.png', description: { en: 'Single-wire surveillance earpiece with in-line PTT.', it: 'Auricolare discreto a filo singolo con PTT sul cavo.' }, role: { en: 'Security and discreet communication', it: 'Sicurezza e comunicazione discreta' }, source: 'https://www.motorolasolutions.com/en_us/products/two-way-radios/commercial-business-two-way-radio-systems/on-site-business-radios/tlk110-radio/tlk110.html/1000.html' },
  { id: 'wp300', maker: 'Motorola Solutions', model: 'WP300', category: 'accessories', image: '/images/equipment/wp300.png', description: { en: 'Wireless Bluetooth control pod with a physical PTT button.', it: 'Comando Bluetooth senza fili con pulsante PTT fisico.' }, role: { en: 'Remote PTT control', it: 'Comando PTT remoto' }, source: 'https://www.motorolasolutions.com/en_us/products/two-way-radios/commercial-business-two-way-radio-systems/on-site-business-radios/tlk110-radio/tlk110.html/1000.html' },
  { id: 'tlk110-charger', maker: 'Motorola Solutions', model: 'TLK 110 multi-unit charger', category: 'accessories', image: '/images/equipment/tlk110-charger.webp', description: { en: 'Six-position charger for TLK 110 radio fleets.', it: 'Caricabatterie a sei postazioni per flotte di radio TLK 110.' }, role: { en: 'Shared equipment management', it: 'Gestione di dispositivi condivisi' }, source: 'https://www.motorolasolutions.com/en_us/products/two-way-radios/commercial-business-two-way-radio-systems/on-site-business-radios/tlk110-radio/tlk110.html/1000.html' },
  { id: 'sc780-harness', maker: 'Hytera', model: 'SC780 chest harness', category: 'accessories', image: '/images/equipment/sc780-harness.png', description: { en: 'Chest harness option for compatible Hytera body cameras.', it: 'Imbragatura toracica per bodycam Hytera compatibili.' }, role: { en: 'Body-worn video mounting', it: 'Fissaggio del video indossabile' }, source: 'https://www.hytera.com/eu/terminal.page/products_terminal_body-worn-camera_sc780' },
]

export const sectors = [
  { slug: 'logistics', title: { en: 'Logistics & transport', it: 'Logistica e trasporti' }, summary: { en: 'Connect drivers, vehicles and dispatch across routes and depots.', it: 'Collega autisti, veicoli e centrale operativa tra percorsi e depositi.' }, image: '/images/dispatch-operation.png', products: ['dkps-radvh-002', 'dkps-radhh-005', 'dkps-radhh-010', 'dkps-radhh-018', 'wp300'] },
  { slug: 'warehousing', title: { en: 'Warehouses & yards', it: 'Magazzini e piazzali' }, summary: { en: 'Keep indoor teams, loading areas and supervisors in contact.', it: 'Collega squadre interne, aree di carico e responsabili.' }, image: '/images/warehouse-real-30824313.jpeg', products: ['dkps-radhh-010', 'dkps-radhh-006', 'dkps-radhh-023', 'dkps-radhh-014', 'rm250'] },
  { slug: 'security', title: { en: 'Security operations', it: 'Operazioni di sicurezza' }, summary: { en: 'Link patrols, supervisors and control rooms, with video where required.', it: 'Collega pattuglie, responsabili e sale controllo, con video dove serve.' }, image: '/images/brief-security.jpeg', products: ['dkps-radhh-010', 'dkps-radhh-011', 'dkps-radhh-018', 'dkps-radhh-025', 'vb400', 'sc780', 'pmln7189', 'pmln7158'] },
  { slug: 'mountain', title: { en: 'Mountain operations', it: 'Operazioni in montagna' }, summary: { en: 'Coordinate piste vehicles, lift personnel and response teams.', it: 'Coordina mezzi pista, personale degli impianti e squadre di intervento.' }, image: '/images/dkps-operational-hero.png', products: ['dkps-radvh-002', 'dkps-radhh-010', 'dkps-radhh-014', 'dkps-radhh-024', 'sc780', 'sc880', 'rm250', 'sc780-harness'] },
] as const
