export type Copy = { en: string; it: string }
export type EquipmentCategory = 'radios' | 'bodycams' | 'accessories'

export type Equipment = {
  id: string
  maker: string
  model: string
  category: EquipmentCategory
  image: string
  description: Copy
  role: Copy
  source: string
}

export const equipment: Equipment[] = [
  { id: 'tlk110', maker: 'Motorola Solutions', model: 'TLK 110', category: 'radios', image: '/images/motorola-tlk110.png', description: { en: 'Portable WAVE PTX radio with a dedicated PTT key.', it: 'Radio portatile WAVE PTX con tasto PTT dedicato.' }, role: { en: 'Mobile field teams', it: 'Squadre mobili sul campo' }, source: 'https://www.motorolasolutions.com/en_xu/products/broadband-push-to-talk/wave-ptx/tlk110-radio/tlk110.html' },
  { id: 'pnc360s', maker: 'Hytera', model: 'PNC360S', category: 'radios', image: '/images/hytera-pnc360s.webp', description: { en: 'Compact PoC radio designed for everyday voice communication.', it: 'Radio PoC compatta per la comunicazione vocale quotidiana.' }, role: { en: 'Warehouses and site teams', it: 'Magazzini e squadre di sede' }, source: 'https://www.hytera.com/eu/products/poc-radio/pnc360s' },
  { id: 'pnc380', maker: 'Hytera', model: 'PNC380', category: 'radios', image: '/images/equipment/pnc380.jpg', description: { en: 'PoC handheld with screen and keypad for group communication.', it: 'Portatile PoC con schermo e tastiera per la comunicazione di gruppo.' }, role: { en: 'Supervisors and site operations', it: 'Responsabili e operazioni di sede' }, source: 'https://www.hytera.com/eu/products/poc-radio/pnc380' },
  { id: 'pnc460', maker: 'Hytera', model: 'PNC460', category: 'radios', image: '/images/equipment/pnc460.png', description: { en: 'Rugged smart device combining PoC radio functions with a camera.', it: 'Dispositivo smart robusto con funzioni radio PoC e fotocamera integrata.' }, role: { en: 'Teams needing voice and visual context', it: 'Team che necessitano di voce e immagini' }, source: 'https://www.hytera.com/eu/products/poc-radio/pnc460' },
  { id: 'tlk150', maker: 'Motorola Solutions', model: 'TLK 150', category: 'radios', image: '/images/equipment/tlk150.jpg', description: { en: 'WAVE PTX mobile radio designed for installation in vehicles.', it: 'Radio veicolare WAVE PTX progettata per l’installazione a bordo.' }, role: { en: 'Fleet and service vehicles', it: 'Flotte e veicoli di servizio' }, source: 'https://www.motorolasolutions.com/en_us/products/two-way-radios/commercial-business-two-way-radio-systems/on-site-business-radios/tlk150-mobile-two-way-radio.html' },
  { id: 'mnc360', maker: 'Hytera', model: 'MNC360', category: 'radios', image: '/images/equipment/mnc360.jpg', description: { en: 'In-vehicle Push-to-Talk over Cellular radio.', it: 'Radio Push-to-Talk over Cellular per installazione su veicolo.' }, role: { en: 'Drivers and mountain vehicles', it: 'Autisti e mezzi di montagna' }, source: 'https://www.hytera.com/eu/terminal.page/products_terminal_poc-radio_mnc360' },
  { id: 'vb400', maker: 'Motorola Solutions', model: 'VB400', category: 'bodycams', image: '/images/equipment/vb400.png', description: { en: 'Body-worn camera for documenting field incidents.', it: 'Bodycam indossabile per documentare gli interventi sul campo.' }, role: { en: 'Security and response teams', it: 'Sicurezza e squadre di intervento' }, source: 'https://www.motorolasolutions.com/en_us/video-security-access-control/body-worn-cameras/vb400.html' },
  { id: 'sc780', maker: 'Hytera', model: 'SC780', category: 'bodycams', image: '/images/equipment/sc780.png', description: { en: 'Connected 4G bodycam with voice communication features.', it: 'Bodycam 4G con funzioni di comunicazione vocale.' }, role: { en: 'Field response and control-room links', it: 'Interventi sul campo e sala controllo' }, source: 'https://www.hytera.com/eu/terminal.page/products_terminal_body-worn-camera_sc780' },
  { id: 'sc880', maker: 'Hytera', model: 'SC880', category: 'bodycams', image: '/images/equipment/sc880.png', description: { en: 'Connected 5G bodycam with PoC communication support.', it: 'Bodycam 5G con supporto alla comunicazione PoC.' }, role: { en: 'Video-enabled field operations', it: 'Operazioni sul campo con video' }, source: 'https://www.hytera.com/eu/products/body-worn-camera/sc880' },
  { id: 'pmln7189', maker: 'Motorola Solutions', model: 'PMLN7189', category: 'accessories', image: '/images/equipment/earpiece.jpg', description: { en: 'Swivel earpiece with in-line microphone and PTT.', it: 'Auricolare orientabile con microfono e PTT sul cavo.' }, role: { en: 'Discreet team communication', it: 'Comunicazione discreta dei team' }, source: 'https://www.motorolasolutions.com/en_xp/products/two-way-radio-accessories/audio-accessories/earpieces/pmln7189.html' },
  { id: 'rm250', maker: 'Motorola Solutions', model: 'RM250 / PMMN4125', category: 'accessories', image: '/images/equipment/rm250.webp', description: { en: 'Remote speaker microphone for compatible portable radios.', it: 'Microfono altoparlante remoto per radio portatili compatibili.' }, role: { en: 'Hands-on work and field teams', it: 'Lavoro manuale e squadre sul campo' }, source: 'https://www.motorolasolutions.com/en_xp/products/two-way-radio-accessories/audio-accessories/remote-speaker-microphones/pmmn4125.html' },
  { id: 'pmln7158', maker: 'Motorola Solutions', model: 'PMLN7158', category: 'accessories', image: '/images/equipment/pmln7158.png', description: { en: 'Single-wire surveillance earpiece with in-line PTT.', it: 'Auricolare discreto a filo singolo con PTT sul cavo.' }, role: { en: 'Security and discreet communication', it: 'Sicurezza e comunicazione discreta' }, source: 'https://www.motorolasolutions.com/en_us/products/two-way-radios/commercial-business-two-way-radio-systems/on-site-business-radios/tlk110-radio/tlk110.html/1000.html' },
  { id: 'wp300', maker: 'Motorola Solutions', model: 'WP300', category: 'accessories', image: '/images/equipment/wp300.png', description: { en: 'Wireless Bluetooth control pod with a physical PTT button.', it: 'Comando Bluetooth senza fili con pulsante PTT fisico.' }, role: { en: 'Remote PTT control', it: 'Comando PTT remoto' }, source: 'https://www.motorolasolutions.com/en_us/products/two-way-radios/commercial-business-two-way-radio-systems/on-site-business-radios/tlk110-radio/tlk110.html/1000.html' },
  { id: 'tlk110-charger', maker: 'Motorola Solutions', model: 'TLK 110 multi-unit charger', category: 'accessories', image: '/images/equipment/tlk110-charger.webp', description: { en: 'Six-position charger for TLK 110 radio fleets.', it: 'Caricabatterie a sei postazioni per flotte di radio TLK 110.' }, role: { en: 'Shared equipment management', it: 'Gestione di dispositivi condivisi' }, source: 'https://www.motorolasolutions.com/en_us/products/two-way-radios/commercial-business-two-way-radio-systems/on-site-business-radios/tlk110-radio/tlk110.html/1000.html' },
  { id: 'sc780-harness', maker: 'Hytera', model: 'SC780 chest harness', category: 'accessories', image: '/images/equipment/sc780-harness.png', description: { en: 'Chest harness option for compatible Hytera body cameras.', it: 'Imbragatura toracica per bodycam Hytera compatibili.' }, role: { en: 'Body-worn video mounting', it: 'Fissaggio del video indossabile' }, source: 'https://www.hytera.com/eu/terminal.page/products_terminal_body-worn-camera_sc780' },
]

export const sectors = [
  { slug: 'logistics', title: { en: 'Logistics & transport', it: 'Logistica e trasporti' }, summary: { en: 'Connect drivers, vehicles and dispatch across routes and depots.', it: 'Collega autisti, veicoli e dispatch tra percorsi e depositi.' }, image: '/images/dispatch-operation.png', products: ['tlk150', 'mnc360', 'tlk110', 'pmln7189'] },
  { slug: 'warehousing', title: { en: 'Warehouses & yards', it: 'Magazzini e piazzali' }, summary: { en: 'Keep indoor teams, loading areas and supervisors in contact.', it: 'Collega squadre interne, aree di carico e responsabili.' }, image: '/images/warehouse-real-30824313.jpeg', products: ['pnc360s', 'pnc380', 'pnc460', 'rm250', 'tlk110-charger'] },
  { slug: 'security', title: { en: 'Security operations', it: 'Operazioni di sicurezza' }, summary: { en: 'Link patrols, supervisors and control rooms, with video where required.', it: 'Collega pattuglie, responsabili e sale controllo, con video dove serve.' }, image: '/images/brief-security.jpeg', products: ['tlk110', 'pnc460', 'vb400', 'sc780', 'pmln7189', 'pmln7158', 'wp300'] },
  { slug: 'mountain', title: { en: 'Mountain operations', it: 'Operazioni in montagna' }, summary: { en: 'Coordinate piste vehicles, lift personnel and response teams.', it: 'Coordina mezzi pista, personale degli impianti e squadre di intervento.' }, image: '/images/dkps-operational-hero.png', products: ['mnc360', 'tlk150', 'pnc360s', 'sc780', 'sc880', 'rm250', 'sc780-harness'] },
] as const
