// English source copy is the stable key. Product and company names remain unchanged.
export const italian: Record<string, string> = {
  // Navigation and shared components
  'Professional communication systems': 'Sistemi di comunicazione professionale',
  'The communication system': 'Il sistema di comunicazione',
  'PTT platform & dispatch': 'Piattaforma PTT e dispatch',
  'Professional radios & devices': 'Radio e dispositivi professionali',
  'Cellular connectivity': 'Connettività cellulare',
  'Industries': 'Settori',
  'Operational solutions': 'Soluzioni operative',
  'Plans & project scope': 'Piani e ambito del progetto',
  'About DKPS': 'Chi è DKPS',
  'Contact': 'Contatti',
  'Home': 'Home',
  'Products': 'Prodotti',
  'Build your system': 'Costruiamo il tuo sistema',
  'Tell us about your operation': 'Parlaci della tua operatività',
  'For existing clients': 'Per i clienti attivi',
  'Made for a working shift.': 'Pensate per il lavoro sul campo.',
  'Examples from professional PoC radio ranges. Models, compatibility and availability are confirmed for each system; these photographs illustrate the type of equipment.': 'Esempi di radio PoC professionali. Modelli, compatibilità e disponibilità sono confermati per ogni sistema; le immagini illustrano il tipo di dispositivo.',
  'Dedicated Push-to-Talk radio example for teams that work away from a desk.': 'Esempio di radio Push-to-Talk dedicata per i team che lavorano lontano da una postazione fissa.',
  'Compact PoC radio example for work that needs simple, immediate voice communication.': 'Esempio di radio PoC compatta per chi ha bisogno di comunicazioni vocali semplici e immediate.',
  'Radios are one part of the DKPS system: connectivity, PTT platform, user groups and dispatch complete the communication path.': 'Le radio sono una parte del sistema DKPS: connettività, piattaforma PTT, gruppi utenti e dispatch completano il percorso di comunicazione.',
  'Find equipment for your operation': 'Troviamo le radio adatte alla tua operatività',
  'Professional radio examples': 'Esempi di radio professionali',
  'FIELD EQUIPMENT / 02': 'DISPOSITIVI SUL CAMPO / 02',
  'PoC / PROFESSIONAL RADIO': 'PoC / RADIO PROFESSIONALE',
  'Page not found': 'Pagina non trovata',
  'System': 'Sistema',
  'Platform': 'Piattaforma',
  'Devices': 'Dispositivi',
  'Solutions': 'Soluzioni',
  'About': 'Azienda',
  'Menu': 'Menu',
  'Close': 'Chiudi',
  'Primary navigation': 'Navigazione principale',
  'Language': 'Lingua',
  'Skip to content': 'Vai al contenuto',
  'DKPS Communications — home': 'DKPS Communications — pagina iniziale',
  'Professional Push-to-Talk communication systems designed around the operation.': 'Sistemi Push-to-Talk professionali progettati attorno alle attività operative.',
  'Architecture': 'Architettura',
  'Radios & devices': 'Radio e dispositivi',
  'Connectivity': 'Connettività',
  'Platform & dispatch': 'Piattaforma e dispatch',
  'Applications': 'Applicazioni',
  'Plans & scope': 'Piani e ambito',
  'Company': 'Azienda',
  'Privacy policy ↗': 'Informativa privacy ↗',
  'Communications designed for the way organisations work.': 'Comunicazioni progettate attorno al lavoro delle organizzazioni.',
  'Next step': 'Prossimo passo',
  'Let’s design the right communication system.': 'Progettiamo il sistema di comunicazione adatto.',
  'Tell us how your teams, sites and vehicles work. We can discuss a system around the operation.': 'Raccontaci come lavorano team, sedi e veicoli. Partiamo dalla tua operatività per definire il sistema.',
  'Discuss your operation': 'Parliamo della tua operatività',
  'Motorola TLK 110 Push-to-Talk radio, manufacturer example': 'Radio Push-to-Talk Motorola TLK 110, esempio del produttore',
  'Hytera PNC360S PoC radio, manufacturer example': 'Radio PoC Hytera PNC360S, esempio del produttore',

  // System data used across pages
  'The point of contact for people in the field.': 'Il punto di contatto per chi lavora sul campo.',
  'Dedicated Push-to-Talk radios, smartphones and fixed or vehicle-based devices can be selected for the way each team works.': 'Radio Push-to-Talk dedicate, smartphone e dispositivi fissi o installati sui veicoli si scelgono in base al lavoro di ciascun team.',
  'The connection between people and locations.': 'Il collegamento tra persone e luoghi.',
  'Cellular data and managed SIM connectivity carry voice and information between devices, sites, vehicles and countries.': 'Dati mobili e SIM gestite trasportano voce e informazioni tra dispositivi, sedi, veicoli e Paesi.',
  'PTT platform': 'Piattaforma PTT',
  'The structure behind every conversation.': 'La struttura dietro ogni conversazione.',
  'The platform routes calls and organises users, groups and communication permissions around the operation.': 'La piattaforma instrada le chiamate e organizza utenti, gruppi e permessi secondo l’operatività.',
  'Dispatch': 'Dispatch',
  'One place to coordinate the operation.': 'Un punto da cui coordinare le attività.',
  'A dispatcher can communicate with teams and use the tools configured for supervision, visibility and response.': 'Un operatore dispatch può comunicare con i team e usare gli strumenti configurati per supervisione, visibilità e risposta.',

  // Homepage
  'Workers coordinating material and forklifts inside a warehouse': 'Operatori al lavoro con materiali e carrelli elevatori in un magazzino',
  'DKPS Communications / Professional Push-to-Talk': 'DKPS Communications / Push-to-Talk professionale',
  'Communication built around your operation.': 'Comunicazioni progettate attorno alla tua operatività.',
  'Every team, site and vehicle. One communication system.': 'Ogni team, sede e veicolo. Un solo sistema di comunicazione.',
  'DKPS brings professional radios, cellular connectivity, a PTT platform and dispatch into one communication system for teams, sites and vehicles.': 'DKPS unisce radio professionali, connettività cellulare, piattaforma PTT e dispatch in un sistema per team, sedi e veicoli.',
  'Explore the system': 'Esplora il sistema',
  'Talk to DKPS': 'Parla con DKPS',
  'Professional radio / manufacturer example': 'Radio professionale / esempio del produttore',
  'Operational context / illustrative photograph': 'Contesto operativo / fotografia illustrativa',
  'FIELD EQUIPMENT / 01': 'DISPOSITIVI SUL CAMPO / 01',
  'DKPS SYSTEM': 'SISTEMA DKPS',
  'Radio / manufacturer example': 'Radio / esempio del produttore',
  'Devices selected to fit the operation.': 'Dispositivi scelti in base al lavoro.',
  'Radio': 'Radio',
  'Radio to dispatch communication path': 'Percorso di comunicazione dalla radio al dispatch',
  'Explore the architecture': 'Esplora l’architettura',
  '01 / System': '01 / Sistema',
  'The radio is one part of the answer.': 'La radio è solo una parte della soluzione.',
  'A working Push-to-Talk system needs equipment, connectivity, a platform and a way to coordinate communication. DKPS considers them together.': 'Un sistema Push-to-Talk richiede dispositivi, connettività, piattaforma e coordinamento. DKPS li progetta insieme.',
  'Communication control': 'Controllo delle comunicazioni',
  'Give every team the right conversations.': 'Ogni team, le conversazioni che gli servono.',
  'Organise the system around departments, locations and responsibilities. Field teams can speak within their groups, supervisors can coordinate across them, and dispatch can reach the operation from one point.': 'Organizza il sistema secondo reparti, sedi e responsabilità. I team comunicano nei propri gruppi, i responsabili li coordinano e il dispatch raggiunge l’intera operazione da un unico punto.',
  'How the structure works': 'Come funziona la struttura',
  'Example communication structure': 'Esempio di struttura delle comunicazioni',
  'Control room': 'Sala controllo',
  'Supervisors': 'Responsabili',
  'Team A': 'Team A',
  'Vehicles': 'Veicoli',
  'Site B': 'Sede B',
  'Illustrative structure · configured to match each organisation': 'Schema illustrativo · configurato per ogni organizzazione',
  '02 / Applications': '02 / Applicazioni',
  'Built for work that does not stand still.': 'Per attività che non si fermano.',
  'Communication requirements change with people, facilities and geography. The system can be planned for the operating pattern, not just the device count.': 'Le esigenze cambiano con persone, strutture e territori. Il sistema segue il modo di lavorare, non solo il numero di dispositivi.',
  'View all industries': 'Vedi tutti i settori',
  'Explore operational solutions': 'Esplora le soluzioni operative',
  'Why DKPS': 'Perché DKPS',
  'One partner across the complete system.': 'Un interlocutore per l’intero sistema.',
  'DKPS brings device selection, platform configuration, connectivity planning and support into a coherent deployment. The goal is a communication structure that reflects how an organisation actually operates.': 'DKPS integra scelta dei dispositivi, configurazione della piattaforma, connettività e assistenza. L’obiettivo è una struttura di comunicazione che rispecchi il lavoro reale dell’organizzazione.',
  'How DKPS works': 'Come lavora DKPS',

  // System page
  'One communication system. Four connected parts.': 'Un sistema di comunicazione. Quattro parti connesse.',
  'From the device in a team member’s hand to the dispatcher coordinating the operation, each part has a clear job. DKPS designs how they work together.': 'Dalla radio nelle mani di un operatore alla postazione dispatch, ogni parte ha un compito preciso. DKPS ne progetta il funzionamento insieme.',
  'Discuss your requirements': 'Parliamo delle tue esigenze',
  '01 / Composition': '01 / Composizione',
  'Follow the path of a message.': 'Segui il percorso di un messaggio.',
  'The system begins with a person pressing Push-to-Talk. Connectivity carries the message to the platform, which routes it to the right people and dispatch point.': 'Tutto inizia quando un operatore preme Push-to-Talk. La rete porta il messaggio alla piattaforma, che lo instrada verso le persone e il dispatch corretti.',
  '02 / Structure': '02 / Struttura',
  'Build communication around the organisation.': 'Organizza le comunicazioni attorno all’azienda.',
  'Communication groups and permissions can follow the real operating structure: who works together, who supervises, and who needs to reach across teams.': 'Gruppi e permessi possono seguire la struttura reale: chi lavora insieme, chi supervisiona e chi deve parlare tra team diversi.',
  'Dispatch and coordination': 'Dispatch e coordinamento',
  'Supervisor': 'Responsabile',
  'Cross-team communication': 'Comunicazione tra team',
  'Department': 'Reparto',
  'Local group management': 'Gestione dei gruppi locali',
  'Field team': 'Team sul campo',
  'Site team': 'Team di sede',
  'Maintenance': 'Manutenzione',
  'Example only. Groups, roles and permissions are designed around each customer’s workflow.': 'Schema esemplificativo. Gruppi, ruoli e permessi vengono definiti sul lavoro di ogni cliente.',
  '03 / Delivery': '03 / Realizzazione',
  'From requirements to a working system.': 'Dalle esigenze a un sistema operativo.',
  'Understand the operation': 'Comprendere l’operatività',
  'Map teams, locations, vehicles, communication paths and points of escalation.': 'Mappare team, sedi, veicoli, flussi di comunicazione e livelli di escalation.',
  'Design the configuration': 'Progettare la configurazione',
  'Choose appropriate devices, connectivity, platform functions and group structure.': 'Scegliere dispositivi, connettività, funzioni della piattaforma e struttura dei gruppi.',
  'Deploy and support': 'Attivare e assistere',
  'Configure the system, onboard users and provide a point of contact for the complete setup.': 'Configurare il sistema, avviare gli utenti e offrire un riferimento per l’intera soluzione.',
  'Make the communication map fit your operation.': 'Adatta la mappa delle comunicazioni alla tua operatività.',

  // Platform
  'Control communication without adding complexity.': 'Controlla le comunicazioni senza aggiungere complessità.',
  'The PTT platform routes voice between users and groups. Dispatch gives authorised operators a place to coordinate people across the operation.': 'La piattaforma PTT instrada la voce tra utenti e gruppi. Il dispatch offre agli operatori autorizzati un punto da cui coordinare il lavoro.',
  'See the complete architecture': 'Scopri l’architettura completa',
  '01 / Dispatch': '01 / Dispatch',
  'A clear line between the field and the control room.': 'Un collegamento diretto tra campo e sala controllo.',
  'A dispatcher console can bring communication groups, location information and operational response into one supervised workflow.': 'La console dispatch può riunire gruppi di comunicazione, informazioni sulla posizione e risposta operativa in un flusso supervisionato.',
  'Warehouse personnel and a vehicle in an operating aisle': 'Operatori e veicolo in una corsia di magazzino',
  'Speak to the right people at the right moment.': 'Parla alle persone giuste nel momento giusto.',
  'Set up teams and priority paths around roles rather than relying on one open channel for everyone. Supervisors and dispatchers can reach individuals or groups as the situation requires.': 'Definisci team e percorsi prioritari in base ai ruoli, senza affidarti a un unico canale aperto a tutti. Responsabili e dispatch possono raggiungere singoli o gruppi secondo la situazione.',
  'Communication groups': 'Gruppi di comunicazione',
  'Users and roles': 'Utenti e ruoli',
  'Dispatcher access': 'Accesso dispatch',
  'Visibility and escalation workflows': 'Visibilità e percorsi di escalation',
  '02 / Capabilities': '02 / Funzioni',
  'The functions available to build from.': 'Le funzioni da cui partire.',
  'The final set of platform capabilities depends on the selected platform, devices and configuration.': 'Le funzioni disponibili dipendono dalla piattaforma, dai dispositivi e dalla configurazione scelti.',
  'Communication': 'Comunicazione',
  'Coordination': 'Coordinamento',
  'Safety & records': 'Sicurezza e registrazioni',
  'Push-to-Talk': 'Push-to-Talk',
  'Voice communication between individuals and groups through compatible devices and the PTT platform.': 'Comunicazione vocale tra persone e gruppi tramite dispositivi compatibili e piattaforma PTT.',
  'Messaging': 'Messaggistica',
  'Text and multimedia communication alongside voice, where supported by the selected platform and devices.': 'Messaggi di testo e contenuti multimediali accanto alla voce, quando supportati da piattaforma e dispositivi scelti.',
  'Video': 'Video',
  'Video sharing can give a dispatcher more context during an operational exchange.': 'La condivisione video può dare più contesto al dispatch durante una comunicazione operativa.',
  'Dispatcher console': 'Console dispatch',
  'A web-based point for authorised operators to reach teams, supervise groups and coordinate responses.': 'Una postazione web per operatori autorizzati, da cui raggiungere team, supervisionare gruppi e coordinare risposte.',
  'Location visibility': 'Visibilità della posizione',
  'Device location and route information can help teams coordinate work across a site or fleet.': 'Posizione dei dispositivi e informazioni sui percorsi possono aiutare a coordinare il lavoro tra sedi e flotte.',
  'Geofencing': 'Geofencing',
  'Location-based zones and alerts can support defined operational workflows.': 'Zone e avvisi basati sulla posizione possono supportare procedure operative definite.',
  'Emergency alert': 'Allarme di emergenza',
  'An SOS workflow can connect a field user with the people responsible for responding.': 'Un flusso SOS può collegare l’operatore sul campo alle persone incaricate della risposta.',
  'Lone worker': 'Operatore isolato',
  'Check-in and escalation workflows can support people working away from a team.': 'Check-in e procedure di escalation possono supportare chi lavora lontano dal team.',
  'Recording & playback': 'Registrazione e riascolto',
  'Where enabled, communication records can support incident review and operational learning.': 'Dove previste, le registrazioni possono aiutare a esaminare gli incidenti e migliorare le procedure.',
  '03 / Administration': '03 / Amministrazione',
  'Manage the system as the organisation changes.': 'Gestisci il sistema mentre l’organizzazione cambia.',
  'Groups & permissions': 'Gruppi e permessi',
  'Define who can communicate within a team and who can reach across departments or sites.': 'Definisci chi comunica nel team e chi può raggiungere altri reparti o sedi.',
  'Users & devices': 'Utenti e dispositivi',
  'Keep the communication structure aligned as people join, move roles or need different equipment.': 'Aggiorna la struttura quando entrano nuove persone, cambiano i ruoli o servono dispositivi diversi.',
  'Integration scope': 'Ambito delle integrazioni',
  'Discuss connections to existing workflows and systems during solution design, based on actual requirements.': 'Valuta i collegamenti con processi e sistemi esistenti durante la progettazione, sulla base delle esigenze reali.',
  'Put platform capabilities to work in a real operation.': 'Porta le funzioni della piattaforma nel lavoro quotidiano.',

  // Devices and connectivity
  'Choose equipment for the people using it.': 'Scegli dispositivi adatti a chi li usa.',
  'A radio should suit the environment, the role and the communication path. DKPS considers devices as part of the system design, not as a separate purchase.': 'Una radio deve adattarsi all’ambiente, al ruolo e al percorso di comunicazione. DKPS sceglie i dispositivi come parte del sistema.',
  'Where devices fit in the system': 'Il ruolo dei dispositivi nel sistema',
  '01 / Equipment': '01 / Dispositivi',
  'Physical tools for different types of work.': 'Strumenti fisici per lavori diversi.',
  'Dedicated PoC radios': 'Radio PoC dedicate',
  'Physical Push-to-Talk controls for teams that need a purpose-built communication device.': 'Comandi Push-to-Talk fisici per team che hanno bisogno di un dispositivo dedicato.',
  'Smartphones & tablets': 'Smartphone e tablet',
  'Compatible apps can bring a mobile device into the communication system where the role allows it.': 'App compatibili possono inserire un dispositivo mobile nel sistema quando il ruolo lo consente.',
  'Vehicle & fixed positions': 'Veicoli e postazioni fisse',
  'Vehicle-mounted and desk-based options can connect moving crews and control points to the same structure.': 'Soluzioni installate su veicoli o postazioni possono collegare squadre mobili e punti di controllo.',
  'Equipment / manufacturer examples': 'Dispositivi / esempi dei produttori',
  'The product has to work in the field.': 'Il dispositivo deve funzionare sul campo.',
  'Motorola WAVE PTX and Hytera PoC are among the device ranges considered for professional communication. The pictured models are illustrative; final models and compatibility are confirmed during system design.': 'Motorola WAVE PTX e Hytera PoC sono tra le gamme considerate per le comunicazioni professionali. I modelli mostrati sono illustrativi; scelta e compatibilità si confermano durante la progettazione.',
  'Discuss your equipment needs': 'Parliamo dei dispositivi necessari',
  '02 / Selection': '02 / Scelta',
  'The device decision follows the work.': 'Il lavoro guida la scelta del dispositivo.',
  'Environment': 'Ambiente',
  'Where will it be carried and used: inside, outdoors, in vehicles or across facilities?': 'Dove verrà usato: al chiuso, all’aperto, sui veicoli o tra più strutture?',
  'Role': 'Ruolo',
  'Who needs instant voice, who needs a screen, and who needs to reach more than one group?': 'Chi ha bisogno di voce immediata, chi di uno schermo e chi deve raggiungere più gruppi?',
  'What cellular conditions and countries matter for the operation?': 'Quali condizioni di rete mobile e quali Paesi contano per l’operatività?',
  'Management': 'Gestione',
  'How will devices and users be provisioned, updated and supported?': 'Come verranno attivati, aggiornati e assistiti utenti e dispositivi?',
  'Select the equipment with the system, not before it.': 'Scegli i dispositivi insieme al sistema.',
  'Plan the connection around where people work.': 'Progetta la connessione dove lavorano le persone.',
  'Push-to-Talk over Cellular depends on suitable network access. DKPS includes SIM and connectivity planning in the wider communication design, including operations across locations and borders.': 'Il Push-to-Talk over Cellular richiede accesso a una rete adatta. DKPS include SIM e connettività nella progettazione complessiva, anche tra sedi e Paesi diversi.',
  'Discuss locations and routes': 'Parliamo di sedi e percorsi',
  '01 / Connectivity': '01 / Connettività',
  'A network layer that supports the operation.': 'Una rete a supporto dell’operatività.',
  'Cellular data': 'Dati mobili',
  'PoC communication uses commercial mobile networks to connect compatible devices with the platform.': 'Le comunicazioni PoC usano reti mobili commerciali per collegare dispositivi compatibili alla piattaforma.',
  'Managed SIMs': 'SIM gestite',
  'Connectivity and device provisioning can be considered together rather than left to each individual team.': 'Connettività e attivazione dei dispositivi possono essere gestite insieme, senza lasciarle ai singoli team.',
  'International planning': 'Pianificazione internazionale',
  'When work crosses borders, the required countries, networks and commercial terms should be checked before deployment.': 'Quando il lavoro attraversa i confini, Paesi, reti e condizioni commerciali vanno verificati prima dell’attivazione.',
  '02 / Design questions': '02 / Domande di progetto',
  'Coverage is a project question.': 'La copertura è una questione di progetto.',
  'Actual service depends on the networks available in the places where your people work. A useful design starts with a map of the operation, not a blanket coverage promise.': 'Il servizio effettivo dipende dalle reti disponibili nei luoghi di lavoro. Il progetto parte dalla mappa dell’operatività, non da una promessa generica di copertura.',
  'Where': 'Dove',
  'Sites, buildings, routes, outdoor areas and countries.': 'Sedi, edifici, percorsi, aree esterne e Paesi.',
  'Who': 'Chi',
  'Which teams must communicate locally, across facilities or internationally?': 'Quali team devono comunicare nella stessa sede, tra strutture o all’estero?',
  'How': 'Come',
  'Which devices, networks and fallback methods fit each environment?': 'Quali dispositivi, reti e alternative sono adatti a ogni ambiente?',
  'Support': 'Assistenza',
  'Who manages SIMs, provisioning and changes as the operation evolves?': 'Chi gestisce SIM, attivazioni e modifiche quando l’operatività cambia?',
  'Tell us where communication needs to work.': 'Dicci dove devono funzionare le comunicazioni.',

  // Industry data
  'Logistics & transport': 'Logistica e trasporti',
  'Vehicles, depots, routes and dispatch need a shared communication structure.': 'Veicoli, depositi, percorsi e dispatch hanno bisogno di una struttura di comunicazione condivisa.',
  'Connect drivers, supervisors and operations teams across moving work.': 'Collega autisti, responsabili e team operativi nel lavoro in movimento.',
  'Hospitality & hotels': 'Hospitality e hotel',
  'Front of house, housekeeping, maintenance and security work on different schedules.': 'Reception, housekeeping, manutenzione e sicurezza lavorano con tempi diversi.',
  'Give each department the groups it needs while preserving a route to supervisors.': 'Dai a ogni reparto i gruppi necessari e un percorso per raggiungere i responsabili.',
  'Manufacturing': 'Produzione industriale',
  'Production, maintenance and management need clear communication across a site.': 'Produzione, manutenzione e direzione hanno bisogno di comunicazioni chiare in tutto lo stabilimento.',
  'Coordinate teams around plant operations and changing priorities.': 'Coordina i team attorno alle attività dell’impianto e alle priorità che cambiano.',
  'Security': 'Sicurezza',
  'Teams need rapid communication between patrols, supervisors and the control room.': 'I team hanno bisogno di contatti rapidi tra pattuglie, responsabili e sala controllo.',
  'Structure field and control-room communication with defined roles and escalation.': 'Organizza le comunicazioni tra campo e sala controllo con ruoli e livelli di escalation definiti.',
  'Construction & engineering': 'Cantieri e ingegneria',
  'Projects bring together crews, subcontractors, vehicles and temporary locations.': 'I progetti riuniscono squadre, subappaltatori, veicoli e sedi temporanee.',
  'Keep site teams and project coordination in contact as the work changes.': 'Mantieni in contatto squadre di cantiere e coordinamento quando il lavoro cambia.',
  'Mountain & resort operations': 'Operazioni in montagna e resort',
  'Lift teams, slope operations, maintenance and guest services work across demanding terrain.': 'Impianti, piste, manutenzione e servizi agli ospiti lavorano su un territorio impegnativo.',
  'Map teams and escalation paths with connectivity assessed for each location.': 'Definisci team e percorsi di escalation valutando la connettività di ogni luogo.',
  'Field service & maintenance': 'Assistenza sul campo e manutenzione',
  'Mobile technicians need a direct route to supervisors and colleagues across sites.': 'I tecnici mobili devono poter raggiungere direttamente responsabili e colleghi tra sedi diverse.',
  'Connect technicians, vehicles and support teams through the relevant groups.': 'Collega tecnici, veicoli e team di supporto tramite i gruppi appropriati.',
  'Ports & maritime': 'Porti e attività marittime',
  'Dockside teams, vehicles and operations staff work across broad facilities.': 'Squadre in banchina, veicoli e operatori lavorano in strutture estese.',
  'Organise communication around terminals, duties and supervisors.': 'Organizza le comunicazioni secondo terminal, compiti e responsabili.',
  'Agriculture & wine': 'Agricoltura e vitivinicolo',
  'Field teams can be spread across estates and seasonal operations.': 'I team sul campo possono essere distribuiti tra tenute e attività stagionali.',
  'Coordinate field work where cellular connectivity is available.': 'Coordina il lavoro sul campo dove è disponibile una connessione mobile.',
  'Cruise operations': 'Operazioni crocieristiche',
  'Shipboard teams and shore operations have distinct communication needs.': 'I team a bordo e le operazioni a terra hanno esigenze di comunicazione diverse.',
  'Plan communication groups and connectivity around the operating environment.': 'Progetta gruppi e connettività in base all’ambiente operativo.',
  'Healthcare': 'Sanità',
  'Facilities need clear escalation between operational and support teams.': 'Le strutture hanno bisogno di percorsi chiari tra team operativi e di supporto.',
  'Configure communication around responsibilities and applicable privacy requirements.': 'Configura le comunicazioni secondo responsabilità e requisiti privacy applicabili.',

  // Solutions data
  'Single site': 'Una sede',
  'Many teams. One facility.': 'Molti team. Un’unica struttura.',
  'A hotel, factory, campus or port can bring departments into a shared system while keeping everyday conversations relevant to each role.': 'Un hotel, stabilimento, campus o porto può unire i reparti in un sistema condiviso, mantenendo le conversazioni pertinenti a ciascun ruolo.',
  'Department groups': 'Gruppi di reparto',
  'Supervisor escalation': 'Escalation ai responsabili',
  'Fixed and mobile users': 'Utenti fissi e mobili',
  'Multi-site': 'Più sedi',
  'One organisation across locations.': 'Un’organizzazione, più luoghi.',
  'A common platform can connect separate facilities and give regional operations a consistent way to coordinate.': 'Una piattaforma comune può collegare strutture separate e offrire alle operazioni regionali un modo coerente di coordinarsi.',
  'Local and cross-site groups': 'Gruppi locali e tra sedi',
  'Central user management': 'Gestione centrale degli utenti',
  'Dispatch across locations': 'Dispatch tra sedi',
  'International operations': 'Operazioni internazionali',
  'Teams that cross borders.': 'Team che attraversano confini.',
  'Plan devices, cellular connectivity and platform access together for people working in more than one country.': 'Progetta insieme dispositivi, connettività mobile e accesso alla piattaforma per chi lavora in più Paesi.',
  'Connectivity planning': 'Pianificazione della connettività',
  'Shared communication structure': 'Struttura di comunicazione condivisa',
  'Support across the system': 'Assistenza per l’intero sistema',
  'Remote workforce': 'Personale sul territorio',
  'People working away from a base.': 'Persone che lavorano lontano dalla sede.',
  'Keep mobile and isolated workers connected to supervisors and response teams where suitable connectivity is available.': 'Mantieni collegati operatori mobili e isolati a responsabili e team di risposta dove è disponibile una connettività adeguata.',
  'Field communication': 'Comunicazione sul campo',
  'Location-aware workflows': 'Procedure basate sulla posizione',
  'Escalation paths': 'Percorsi di escalation',
  'Event communications': 'Comunicazioni per eventi',
  'Temporary teams, changing roles.': 'Team temporanei, ruoli che cambiano.',
  'Organise event staff, operations, security and control teams around a defined communication plan.': 'Organizza personale, operazioni, sicurezza e controllo dell’evento attorno a un piano di comunicazione definito.',
  'Temporary groups': 'Gruppi temporanei',
  'Role-based access': 'Accesso basato sui ruoli',
  'Control-room coordination': 'Coordinamento dalla sala controllo',

  // Plans data
  'A single operation': 'Una singola operazione',
  'Connected devices or compatible smartphones': 'Dispositivi connessi o smartphone compatibili',
  'Core group communication': 'Comunicazione di gruppo essenziale',
  'Configuration and support': 'Configurazione e assistenza',
  'Several teams or locations': 'Più team o sedi',
  'A wider device mix': 'Una gamma più ampia di dispositivi',
  'More coordination workflows': 'Più procedure di coordinamento',
  'Additional platform functions as required': 'Funzioni aggiuntive della piattaforma secondo necessità',
  'Central management': 'Gestione centrale',
  'Complex or international operations': 'Operazioni complesse o internazionali',
  'Professional device planning': 'Pianificazione dei dispositivi professionali',
  'Multi-country connectivity planning': 'Pianificazione della connettività in più Paesi',
  'Dispatch and integration scope': 'Ambito di dispatch e integrazioni',
  'Managed deployment and support': 'Attivazione e assistenza gestite',

  // Secondary pages
  'Different environments. Clear communication.': 'Ambienti diversi. Comunicazioni chiare.',
  'DKPS describes applications across transport, facilities, hospitality, industry and field work. Each environment changes the way teams, sites and control points should be connected.': 'DKPS presenta applicazioni per trasporti, strutture, hospitality, industria e lavoro sul campo. Ogni ambiente richiede collegamenti diversi tra team, sedi e punti di controllo.',
  'Explore operating patterns': 'Esplora i modelli operativi',
  '01 / Environments': '01 / Ambienti',
  'Start with the work on the ground.': 'Parti dal lavoro sul campo.',
  'Discuss this context': 'Parliamo di questo contesto',
  'Your industry is only the starting point.': 'Il settore è solo il punto di partenza.',
  'The useful detail is how your own teams, locations and responsibilities work together.': 'Conta come collaborano i tuoi team, le sedi e le persone responsabili.',
  'Start with the shape of the operation.': 'Parti dalla struttura dell’operatività.',
  'A single site, a network of facilities or a travelling workforce calls for different communication paths. DKPS configures the elements around that structure.': 'Una sede, una rete di strutture o personale in movimento richiedono percorsi di comunicazione diversi. DKPS configura il sistema attorno a quella struttura.',
  'See the system architecture': 'Scopri l’architettura del sistema',
  '01 / Operating patterns': '01 / Modelli operativi',
  'Five ways to frame the requirement.': 'Cinque modi di descrivere l’esigenza.',
  'Discuss this operation': 'Parliamo di questa operazione',
  'Describe your operation. We will map the communication.': 'Descrivi la tua operatività. Progetteremo le comunicazioni.',
  'A system proposal should show what is included.': 'Una proposta deve chiarire cosa comprende il sistema.',
  'DKPS offers three solution levels. Equipment, platform functions, connectivity and support are scoped around each deployment; no fixed price is shown here.': 'DKPS presenta tre livelli di soluzione. Dispositivi, funzioni, connettività e assistenza vengono definiti per ogni progetto; qui non sono indicati prezzi fissi.',
  'Request a scoped proposal': 'Richiedi una proposta su misura',
  '01 / Starting points': '01 / Punti di partenza',
  'A commercial structure for different levels of complexity.': 'Una struttura commerciale per livelli diversi di complessità.',
  'These are starting points for a conversation, not fixed technical specifications or a checkout catalogue.': 'Sono punti di partenza per una conversazione, non specifiche tecniche fisse né un catalogo da acquistare online.',
  'Discuss scope': 'Definiamo l’ambito',
  '02 / Proposal': '02 / Proposta',
  'What a useful quote needs to cover.': 'Cosa deve comprendere un preventivo utile.',
  'Equipment': 'Dispositivi',
  'Device types, quantities and accessories matched to roles and environments.': 'Tipi, quantità e accessori dei dispositivi adatti a ruoli e ambienti.',
  'Required communication groups, dispatch access and relevant capabilities.': 'Gruppi di comunicazione, accesso dispatch e funzioni necessarie.',
  'Locations, routes, countries and SIM management requirements.': 'Sedi, percorsi, Paesi e gestione delle SIM.',
  'Deployment & support': 'Attivazione e assistenza',
  'Configuration, onboarding, ongoing management and commercial terms.': 'Configurazione, avvio, gestione continuativa e condizioni commerciali.',
  'Ask for a proposal shaped around your operation.': 'Richiedi una proposta per la tua operatività.',
  'DKPS approaches communication as a system.': 'DKPS affronta la comunicazione come un sistema.',
  'DKPS designs and integrates professional Push-to-Talk over Cellular solutions. The focus is the operating structure behind the device.': 'DKPS progetta e integra soluzioni professionali Push-to-Talk over Cellular. Il punto centrale è l’organizzazione del lavoro dietro il dispositivo.',
  'Start a conversation': 'Iniziamo a parlarne',
  '01 / Approach': '01 / Approccio',
  'The complete chain belongs in one conversation.': 'L’intera catena va progettata insieme.',
  'Buying radios alone does not decide who can reach whom, how sites connect, what dispatch sees or who supports a changing organisation. DKPS brings those decisions into the same design process.': 'Acquistare radio non basta a decidere chi può parlare con chi, come si collegano le sedi, cosa vede il dispatch o chi assiste l’organizzazione. DKPS affronta queste scelte in un unico processo.',
  'Design': 'Progettare',
  'Understand teams, locations and communication hierarchy.': 'Comprendere team, sedi e gerarchie di comunicazione.',
  'Integrate': 'Integrare',
  'Bring equipment, connectivity, platform and dispatch into a coherent setup.': 'Unire dispositivi, connettività, piattaforma e dispatch in una soluzione coerente.',
  'Keep one point of contact for the system as operational needs change.': 'Mantenere un riferimento per il sistema quando cambiano le esigenze operative.',
  '02 / Technology choices': '02 / Scelte tecnologiche',
  'Choose for fit, not for a catalogue page.': 'Scegli in base all’utilizzo, non al catalogo.',
  'The DKPS offer brings Motorola Solutions and Hytera device ranges together with platform and SIM services. Hardware and functions are confirmed for each deployment.': 'La proposta DKPS combina gamme Motorola Solutions e Hytera con piattaforma e servizi SIM. Dispositivi e funzioni si confermano per ogni progetto.',
  '03 / Working with DKPS': '03 / Lavorare con DKPS',
  'A practical sequence from brief to use.': 'Un percorso concreto dalle esigenze all’uso.',
  'Operational brief': 'Analisi operativa',
  'Describe teams, locations, routes, devices and existing communication gaps.': 'Descrivere team, sedi, percorsi, dispositivi e problemi di comunicazione attuali.',
  'System design': 'Progetto del sistema',
  'Agree the communication structure, technology choices and deployment scope.': 'Definire struttura delle comunicazioni, tecnologie e ambito di attivazione.',
  'Configuration & support': 'Configurazione e assistenza',
  'Set up the chosen system and define ownership for ongoing changes and assistance.': 'Configurare il sistema e stabilire come gestire modifiche e assistenza nel tempo.',

  // Contact and missing pages
  'Tell us how communication works today.': 'Raccontaci come comunicate oggi.',
  'A useful conversation starts with teams, facilities, vehicles and the people who coordinate them. DKPS can then discuss an appropriate Push-to-Talk system.': 'Partiamo da team, strutture, veicoli e persone che li coordinano. Da lì possiamo definire un sistema Push-to-Talk adatto.',
  '01 / Enquiry': '01 / Richiesta',
  'Describe the operation.': 'Descrivi l’operatività.',
  'This form opens an email draft in your own mail app. You can review it before sending; no details are transmitted until you send that email.': 'Il modulo apre una bozza nella tua app email. Puoi controllarla prima di inviarla; nessun dato viene trasmesso finché non invii il messaggio.',
  'Full name': 'Nome e cognome',
  'Work email': 'Email aziendale',
  'Company or organisation': 'Azienda o organizzazione',
  'What needs to be connected?': 'Che cosa va collegato?',
  'Teams, sites, vehicles, countries, control room, current challenges…': 'Team, sedi, veicoli, Paesi, sala controllo, problemi attuali…',
  'Open email draft': 'Apri la bozza email',
  'Your email app should open a draft. Review it there before sending.': 'La tua app email dovrebbe aprire una bozza. Controllala prima di inviarla.',
  'Direct contact': 'Contatto diretto',
  'Prefer to write directly?': 'Preferisci scrivere direttamente?',
  'Helpful context to include': 'Informazioni utili da includere',
  'Teams and departments': 'Team e reparti',
  'Sites, vehicles and routes': 'Sedi, veicoli e percorsi',
  'Countries of operation': 'Paesi in cui operate',
  'Current radios or communication tools': 'Radio o strumenti attuali',
  'Who needs dispatch or supervision': 'Chi ha bisogno di dispatch o supervisione',
  'That route is not part of this site.': 'Questa pagina non fa parte del sito.',
  'Use the navigation to explore the DKPS system, or return to the homepage.': 'Usa il menu per esplorare il sistema DKPS o torna alla pagina iniziale.',
  'Return home': 'Torna alla pagina iniziale',
}
